// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task.Models;

#nullable disable

namespace Task.Models.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20250630090730_MVCTaskAddRelationShips")]
    partial class MVCTaskAddRelationShips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task.Models.Entities.CRSResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CRSId")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CRSId");

                    b.HasIndex("TraineeId");

                    b.ToTable("CRSResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CRSId = 1,
                            Degree = 85,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CRSId = 2,
                            Degree = 78,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CRSId = 3,
                            Degree = 90,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 4,
                            CRSId = 4,
                            Degree = 65,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 5,
                            CRSId = 5,
                            Degree = 92,
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 6,
                            CRSId = 1,
                            Degree = 88,
                            TraineeId = 5
                        },
                        new
                        {
                            Id = 7,
                            CRSId = 2,
                            Degree = 74,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 8,
                            CRSId = 3,
                            Degree = 81,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 9,
                            CRSId = 4,
                            Degree = 59,
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 10,
                            CRSId = 5,
                            Degree = 95,
                            TraineeId = 5
                        });
                });

            modelBuilder.Entity("Task.Models.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("MaxDegree")
                        .HasColumnType("int");

                    b.Property<int>("MinDegree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptId = 1,
                            Hours = 3,
                            MaxDegree = 100,
                            MinDegree = 50,
                            Name = "Math"
                        },
                        new
                        {
                            Id = 2,
                            DeptId = 1,
                            Hours = 4,
                            MaxDegree = 100,
                            MinDegree = 45,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            DeptId = 2,
                            Hours = 3,
                            MaxDegree = 100,
                            MinDegree = 50,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            DeptId = 3,
                            Hours = 5,
                            MaxDegree = 100,
                            MinDegree = 60,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 5,
                            DeptId = 3,
                            Hours = 4,
                            MaxDegree = 100,
                            MinDegree = 50,
                            Name = "Networks"
                        });
                });

            modelBuilder.Entity("Task.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerName = "Dr. Nader",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            ManagerName = "Dr. Laila",
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            ManagerName = "Dr. Amin",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            ManagerName = "Dr. Safaa",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 5,
                            ManagerName = "Dr. Tamer",
                            Name = "Networks"
                        });
                });

            modelBuilder.Entity("Task.Models.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("CRSId")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CRSId");

                    b.HasIndex("DeptId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            CRSId = 1,
                            DeptId = 1,
                            Image = "ahmed.png",
                            Name = "Ahmed Samir",
                            Salary = 15000
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            CRSId = 2,
                            DeptId = 1,
                            Image = "sara.png",
                            Name = "Sara Hany",
                            Salary = 14000
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alex",
                            CRSId = 3,
                            DeptId = 2,
                            Name = "Tamer Youssef",
                            Salary = 16000
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mansoura",
                            CRSId = 4,
                            DeptId = 3,
                            Image = "nourhan.png",
                            Name = "Nourhan Taha",
                            Salary = 14500
                        },
                        new
                        {
                            Id = 5,
                            DeptId = 5,
                            Name = "Hossam Reda",
                            Salary = 13000
                        });
                });

            modelBuilder.Entity("Task.Models.Entities.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            DeptId = 1,
                            Grade = 85,
                            Image = "ali.png",
                            Name = "Ali Hassan"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            DeptId = 1,
                            Grade = 92,
                            Image = "mona.png",
                            Name = "Mona Gamal"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alex",
                            DeptId = 2,
                            Grade = 78,
                            Name = "Ibrahim Said"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mansoura",
                            DeptId = 3,
                            Grade = 88,
                            Image = "reem.jpg",
                            Name = "Reem Adel"
                        },
                        new
                        {
                            Id = 5,
                            DeptId = 3,
                            Grade = 73,
                            Name = "Tarek Helmy"
                        });
                });

            modelBuilder.Entity("Task.Models.Entities.CRSResult", b =>
                {
                    b.HasOne("Task.Models.Entities.Course", "Course")
                        .WithMany("CRSResults")
                        .HasForeignKey("CRSId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Task.Models.Entities.Trainee", "Trainee")
                        .WithMany("CRSResults")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Task.Models.Entities.Course", b =>
                {
                    b.HasOne("Task.Models.Entities.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Task.Models.Entities.Instructor", b =>
                {
                    b.HasOne("Task.Models.Entities.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CRSId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Task.Models.Entities.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Task.Models.Entities.Trainee", b =>
                {
                    b.HasOne("Task.Models.Entities.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Task.Models.Entities.Course", b =>
                {
                    b.Navigation("CRSResults");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Task.Models.Entities.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("Task.Models.Entities.Trainee", b =>
                {
                    b.Navigation("CRSResults");
                });
#pragma warning restore 612, 618
        }
    }
}
